### ISSUE TITLE
change_symbols

### ISSUE THREAD

**Issue by jovo123** [lief-project/tutorials#1]
I was trying out lief and when I followed along the ELF_change_symbols tutorial for python I could not get past this when I run script.py

hashme_pow_sym = next(filter(lambda e : e.name == "pow", hashme.imported_symbols))
TypeError: list object is not an iterator

**Comment by romainthomas** [comment]
It was an error due to Python 2.7. Fixed with https://github.com/lief-project/tutorials/commit/daac9e495a4cae7e51d141b1c6231af82613c211
