### ISSUE TITLE
Segmentation fault for 04_ELF_hooking

### ISSUE THREAD

**Issue by liujian883** [lief-project/tutorials#3]
Hello, 
I tested the 04_ELF_hooking example.
Then I added some code, that is, I added a static incr function, and then the hook function called the incr function
I found that if I removed the compilation options **-Os** from GCC and ran do_math.bin, it would cause a segment fault, and if I added the **-Os** option, it would be fine.May I ask what causes this?
```
static double incr(double x)
{
  return x+1;
}
double hook(double x) {
  return incr(x) + 1 ;
  //return (double)((int)x + 3);
}
```
`$(CC) -Wl,--script=./map.ld -Os  -nostdlib -nodefaultlibs -fPIC -Wl,-shared $^ -o $@`

**Comment by romainthomas** [comment]
Yes, if you remove the ``-Os`` flag the assembly code generated contains **data** (and thus, not pure assembly code)
