### ISSUE TITLE
LIEF 0.10.1 : 04_ELF_hooking broken - cos function does not exist in output lib.so.6 file

### ISSUE THREAD

**Issue by pdreiter** [lief-project/tutorials#4]
When running the 04_ELF_hooking example, `make run`, I get a SegFault.

Looking more closely at the generated so file, the hook function code does not exist in the output ./lib.so.6 file:

`%> nm -gD ./libm.so.6  | egrep -w 'cos'`
`000000000038d0d0 i cos`

`%> gdb -batch -ex 'file ./libm.so.6' -ex 'disassemble cos'`
```
warning: Loadable section ".note.gnu.build-id" outside of ELF segments
warning: Loadable section ".note.ABI-tag" outside of ELF segments
No function contains specified address.
```

- python3.6 
- LIEF 0.10.1
- Ubuntu 18.10
- gcc 8.3.0

**Comment by navytux** [comment]
The crash here was likely due to that system's libm.so exposed cos as GNU_IFUNC symbol: https://github.com/lief-project/LIEF/pull/890 , https://github.com/lief-project/tutorials/pull/8.
